### ISSUE TITLE
Improve command line generator for controllers

### ISSUE THREAD

**Issue by vladimino** [MagedAhmad/PHP-microframework#20]
Here we'll continue an effort to standardize the project's structure.

**To-do**:

- [x] Rename `project.php` into `console`
- [x] Move it from the project root into `bin` folder
- [x] Actualize all namespaces in generator's use statements
- [x] Rename `ControllerCommand` to include a verb (`CreateControllerCommand`?)
- [x] Actualize all file paths in reading/writing operations inside command file
